version: '3'
services:
  drupal:
    volumes:
      - drupal:/var/www/html
    image: drupal:8.8.5-apache
    ports:
      - "8081:80"
    networks:
      - net
  postgres:
    image: postgres:12.2
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    networks:
      - net
volumes:
  drupal:
networks:
  net: