version: '3'
services: 
  db:
    container_name: wp_mysql
    image: mysql:5.7
    volumes:
      - $PWD/data:/var/lib/mysql
    env_file: env_file.txt
    ports:
      - "3306:3306"
    networks:
      - wp_net
  
  wpapp:
    container_name: wp_web
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    image: wordpress
    ports:
      - "8081:80"
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
    - wp_net

networks:
    wp_net:
      
